package com.apidocprotector.enumerator;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ApiDocProtectorAuditEnum {

    GENERATOR_STARTED(1, "The GENERATOR form to new account has been started"),
    GENERATOR_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    GENERATOR_EXCEPTION(5, "{custom message}"),
    GENERATOR_GLASS_EXCEPTION(6, "{custom message}"),
    GENERATOR_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    GENERATOR_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    GENERATOR_VIEW_FORM(9, "View Form was called by GENERATOR"),
    GENERATOR_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    GENERATOR_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    GENERATOR_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    GENERATOR_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    GENERATOR_FORM_USER_CREATED(14, "The user was created successful"),
    GENERATOR_MAIL_SENDER_OK(15, "The mail has been sended to user"),

    ACTIVATOR_STARTED(17, "The ACTIVATOR account has been started"),
    ACTIVATOR_TOKEN_OK(18, "The current token was ok"),
    ACTIVATOR_MAIL_SUCCESSFUL(19, "An email has been sent to current user account"),
    ACTIVATOR_FINISHED(20, "The ACTIVATOR finished successful"),
    ACTIVATOR_EXPIRED_ACCOUNT(21, "Expired Account Token"),
    ACTIVATOR_ACCOUNT_ALREADY_ACTIVATED(22, "The account was already activated"),
    ACTIVATOR_ACCOUNT_NOT_FOUND(23, "{custom message}"),

    INITIALIZER_STARTED(24, "The INITIALIZER has been started"),
    INITIALIZER_TOKEN_OK(25, "{custom message}"),
    INITIALIZER_ERROR(26, "The current user is not activated"),
    INITIALIZER_ENVIRONMENT_OK(27, "The environment has been inialized"),
    INITIALIZER_SESSION_PREPARE_OK(27, "The session has been configured"),
    INITIALIZER_GLASS_STARTED(28, "The INITIALIZER glass was called"),
    INITIALIZER_EXCEPTION(29, "{custom message}"),
    INITIALIZER_DENIED(30, "Access denied, missing token"),
    INITIALIZER_BURNED(31, "The INITIALIZER was burned"),
    INITIALIZER_SUCCESSFUL(32, "The INITIALIZER has been finished"),
    INITIALIZER_SESSION_NOT_FOUND(33, "The session was not found to INITIALIZER"),
    INITIALIZER_FORM_STARTED(34, "The INITIALIZER form was called"),

    SWAGGER_ROUTER_SIGN(35, "The SWAGGER ROUTER was posted to sign"),
    SWAGGER_ROUTER_DETAILS(36, "{custom message}"),
    SWAGGER_ROUTER_STOPBY_SHIELD(37, "The request has been stopped by shiled"),
    SWAGGER_ROUTER_MISSING_USERNAME(38, "The username received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_MISSING_PASSWORD(39, "The password received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXPIRED_SESSION(40, "The session was expired in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXCEPTION(41, "{custom message}"),
    SWAGGER_ROUTER_SESSION_FOUNDED(42, "The current request was running at moment"),
    SWAGGER_ROUTER_LOGIN_ERROR(43, "{custom message}"),
    SWAGGER_ROUTER_LOGIN_OK(44, "{custom message}"),
    SWAGGER_ROUTER_REFRESH_STARTED(45, "The refresh was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_REFRESH_OK(46, "The refresh was finished in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ROUTES_STARTED(47, "The routes was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_DENIED_STARTED(48, "The denied was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ERROR_STARTED(49, "{custom message}"),

    PASSWORD_STARTED(50, "The PASSWORD process has been started"),
    PASSWORD_GLASS_STARTED(51, "The PASSWORD glass has been started"),
    PASSWORD_EXCEPTION(52, "{custom message}"),
    PASSWORD_GLASS_EXCEPTION(53, "{custom message}"),
    PASSWORD_FORM_STARTED(54, "The PASSWORD form has been loaded"),
    PASSWORD_FORM_INVALID_ACCCESS(55, "The APD-USER-PASSWORD session was not ok"),
    PASSWORD_VIEW_FORM(56, "View password was called by PASSWORD"),
    PASSWORD_CHANGED_SUCCESSFUL(57, "An password was changed from PASSWORD"),
    PASSWORD_DATA_POST(58, "Was posted to create a new account from PASSWORD"),
    PASSWORD_FORM_INVALID_SESSION(59, "Invalid session to change a password"),
    PASSWORD_MAIL_SENDER_OK(60, "The mail has been sended to user"),
    PASSWORD_ACCOUNT_NOT_FOUND(61, "{custom message}"),

    PASSWORD_RECOVERY_STARTED(62, "The PASSWORD RECOVERY process has been started"),
    PASSWORD_RECOVERY_GLASS_STARTED(63, "The PASSWORD RECOVERY glass has been started"),
    PASSWORD_RECOVERY_EXCEPTION(64, "{custom message}"),
    PASSWORD_RECOVERY_GLASS_EXCEPTION(65, "{custom message}"),
    PASSWORD_RECOVERY_FORM_STARTED(66, "The PASSWORD RECOVERY form has been loaded"),
    PASSWORD_RECOVERY_FORM_INVALID_ACCCESS(67, "The APD-USER-PASSWORD-RECOVERY session was not ok"),
    PASSWORD_RECOVERY_VIEW_FORM(68, "View password was called by PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_SUCCESSFUL(69, "An password was recovered from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_DATA_POST(70, "Was posted to create a new account from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_FORM_INVALID_SESSION(71, "Invalid session to recovery a password"),
    PASSWORD_RECOVERY_MAIL_SENDER_OK(72, "The mail has been sended to user"),
    PASSWORD_RECOVERY_USER_NOT_FOUND(73, "{custom message}"),

    RECOVERY_STARTED(1, "The RECOVERY account has been started"),
    RECOVERY_GLASS_STARTED(3, "The RECOVERY glass has been started"),
    RECOVERY_EXCEPTION(5, "{custom message}"),
    RECOVERY_GLASS_EXCEPTION(6, "{custom message}"),
    RECOVERY_FORM_STARTED(7, "The RECOVERY form has been loaded"),
    RECOVERY_FORM_INVALID_ACCCESS(8, "The APD-USER-RECOVERY session was not ok"),
    RECOVERY_VIEW_FORM(9, "View Form was called by RECOVERY"),
    RECOVERY_ACCOUNT_SUCCESSFUL(10, "An account was recovered from RECOVERY"),
    RECOVERY_DATA_POST(11, "Was posted to recovery a account from RECOVERY"),
    RECOVERY_FORM_INVALID_SESSION(12, "Invalid session to recovery acccount"),
    RECOVERY_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    RECOVERY_FORM_USER_CREATED(14, "The user was recovered successful"),
    RECOVERY_MAIL_SENDER_OK(15, "The mail has been sended to user"),

    SENTINEL_STARTED(1, "The GENERATOR form to new account has been started"),
    SENTINEL_GLASS_FORWARD(2, "forward: forwardToGeneratorGlass was running"),
    SENTINEL_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    SENTINEL_EXCEPTION(5, "{custom message}"),
    SENTINEL_GLASS_EXCEPTION(6, "{custom message}"),
    SENTINEL_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    SENTINEL_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    SENTINEL_VIEW_FORM(9, "View Form was called by GENERATOR"),
    SENTINEL_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    SENTINEL_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    SENTINEL_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    SENTINEL_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    SENTINEL_FORM_USER_CREATED(14, "The user was created successful"),
    SENTINEL_MAIL_SENDER_OK(15, "The mail has been sended to user"),
    SENTINEL_FORM_REDIRECT(16, "redirect: redirecting to form was running"),

    REDIRECT_STARTED(1, "The GENERATOR form to new account has been started"),
    FORWARD_TO_GENERATOR_GLASS(2, "forward: forwardToGeneratorGlass was running"),
    REDIRECT_GLASS_FORWARD(2, "forward: forwardToGeneratorGlass was running"),
    REDIRECT_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    REDIRECT_EXCEPTION(5, "{custom message}"),
    REDIRECT_GLASS_EXCEPTION(6, "{custom message}"),
    REDIRECT_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    REDIRECT_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    REDIRECT_VIEW_FORM(9, "View Form was called by GENERATOR"),
    REDIRECT_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    REDIRECT_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    REDIRECT_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    REDIRECT_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    REDIRECT_FORM_USER_CREATED(14, "The user was created successful"),
    REDIRECT_MAIL_SENDER_OK(15, "The mail has been sended to user"),
    REDIRECT_TO_GENERATOR_FORM(16, "redirect: redirecting to form was running"),

    LIBRARY_STARTED(1, "The GENERATOR form to new account has been started"),
    LIBRARY_GLASS_FORWARD(2, "forward: forwardToGeneratorGlass was running"),
    LIBRARY_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    LIBRARY_EXCEPTION(5, "{custom message}"),
    LIBRARY_GLASS_EXCEPTION(6, "{custom message}"),
    LIBRARY_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    LIBRARY_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    LIBRARY_VIEW_FORM(9, "View Form was called by GENERATOR"),
    LIBRARY_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    LIBRARY_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    LIBRARY_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    LIBRARY_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    LIBRARY_FORM_USER_CREATED(14, "The user was created successful"),
    LIBRARY_MAIL_SENDER_OK(15, "The mail has been sended to user"),
    LIBRARY_FORM_REDIRECT(16, "redirect: redirecting to form was running"),

    SECURITY_STARTED(1, "The GENERATOR form to new account has been started"),
    SECURITY_GLASS_FORWARD(2, "forward: forwardToGeneratorGlass was running"),
    SECURITY_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    SECURITY_EXCEPTION(5, "{custom message}"),
    SECURITY_GLASS_EXCEPTION(6, "{custom message}"),
    SECURITY_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    SECURITY_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    SECURITY_VIEW_FORM(9, "View Form was called by GENERATOR"),
    SECURITY_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    SECURITY_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    SECURITY_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    SECURITY_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    SECURITY_FORM_USER_CREATED(14, "The user was created successful"),
    SECURITY_MAIL_SENDER_OK(15, "The mail has been sended to user"),
    SECURITY_FORM_REDIRECT(16, "redirect: redirecting to form was running"),

    MAILSENDER_STARTED(1, "The GENERATOR form to new account has been started"),
    MAILSENDER_GLASS_FORWARD(2, "forward: forwardToGeneratorGlass was running"),
    MAILSENDER_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    MAILSENDER_EXCEPTION(5, "{custom message}"),
    MAILSENDER_GLASS_EXCEPTION(6, "{custom message}"),
    MAILSENDER_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    MAILSENDER_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    MAILSENDER_VIEW_FORM(9, "View Form was called by GENERATOR"),
    MAILSENDER_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    MAILSENDER_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    MAILSENDER_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    MAILSENDER_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    MAILSENDER_FORM_USER_CREATED(14, "The user was created successful"),
    MAILSENDER_MAIL_SENDER_OK(15, "The mail has been sended to user"),
    MAILSENDER_FORM_REDIRECT(16, "redirect: redirecting to form was running"),

    VIEW_ERROR_STARTED(50, "The view ERROR has been started"),
    VIEW_ERROR_FINISHED(51, "The view ERROR has been finished"),

    VIEW_GENERATOR_STARTED(51, "{custom message}"),
    VIEW_GENERATOR_FINISHED(52, "{custom message}"),
    VIEW_GENERATOR_ERROR(53, "{custom message}"),
    VIEW_GENERATOR_EXCEPTION(54, "{custom message}"),

    VIEW_RECOVERY_STARTED(55, "{custom message}"),
    VIEW_RECOVERY_FINISHED(56, "{custom message}"),
    VIEW_RECOVERY_ERROR(57, "{custom message}"),
    VIEW_RECOVERY_EXCEPTION(58, "{custom message}"),

    VIEW_PASSWORD_STARTED(59, "{custom message}"),
    VIEW_PASSWORD_FINISHED(60, "{custom message}"),
    VIEW_PASSWORD_ERROR(61, "{custom message}"),
    VIEW_PASSWORD_EXCEPTION(62, "{custom message}"),

    VIEW_PASSWORD_RECOVERY_STARTED(63, "{custom message}"),
    VIEW_PASSWORD_RECOVERY_FINISHED(64, "{custom message}"),
    VIEW_PASSWORD_RECOVERY_ERROR(65, "{custom message}"),
    VIEW_PASSWORD_RECOVERY_EXCEPTION(66, "{custom message}"),

    VIEW_FORM_STARTED(67, "{custom message}"),
    VIEW_FORM_FINISHED(68, "{custom message}"),
    VIEW_FORM_ERROR(69, "{custom message}"),
    VIEW_FORM_EXCEPTION(70, "{custom message}"),

    VIEW_INDEX_STARTED(71, "{custom message}"),
    VIEW_INDEX_FINISHED(72, "{custom message}"),
    VIEW_INDEX_ERROR(73, "{custom message}"),
    VIEW_INDEX_EXCEPTION(74, "{custom message}"),

    VIEW_REFRESHED_STARTED(75, "{custom message}"),
    VIEW_REFRESHED_FINISHED(76, "{custom message}"),
    VIEW_REFRESHED_ERROR(77, "{custom message}"),
    VIEW_REFRESHED_EXCEPTION(78, "{custom message}"),

    VIEW_PROTECTOR_STARTED(79, "{custom message}"),
    VIEW_PROTECTOR_FINISHED(80, "{custom message}"),
    VIEW_PROTECTOR_ERROR(81, "{custom message}"),
    VIEW_PROTECTOR_EXCEPTION(82, "{custom message}"),

    GENERIC_MESSAGE(20000, ""),
    SESSION_PREPARED_OK(20001, "Session created successful"),
    SESSION_FOUNDED(20001, "Session founded successful");

    public int code;
    public String message;

}
