package com.apidocprotector.enumerator;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ApiDocProtectorAuditEnum {

    GENERATOR_STARTED(1, "The GENERATOR form to new account has been started"),
    GENERATOR_GLASS_STARTED(3, "The GENERATOR glass has been started"),
    GENERATOR_EXCEPTION(5, "{custom message}"),
    GENERATOR_GLASS_EXCEPTION(6, "{custom message}"),
    GENERATOR_FORM_STARTED(7, "The GENERATOR form to new account has been loaded"),
    GENERATOR_FORM_INVALID_ACCCESS(8, "The APD-USER-GENERATOR session was not ok"),
    GENERATOR_VIEW_FORM(9, "View Form was called by GENERATOR"),
    GENERATOR_ACCOUNT_CREATED(10, "An account was created from GENERATOR"),
    GENERATOR_DATA_POST(11, "Was posted to create a new account from GENERATOR"),
    GENERATOR_FORM_INVALID_SESSION(12, "Invalid session to create a new acccount"),
    GENERATOR_FORM_USER_ALREADY_EXISTS(13, "The user or email already exists"),
    GENERATOR_MAIL_SENDER_OK(15, "The mail has been sended to user"),

    ACTIVATOR_STARTED(17, "The ACTIVATOR account has been started"),
    ACTIVATOR_TOKEN_OK(18, "The current token was ok"),
    ACTIVATOR_MAIL_SUCCESSFUL(19, "An email has been sent to current user account"),
    ACTIVATOR_FINISHED(20, "The ACTIVATOR finished successful"),
    ACTIVATOR_EXPIRED_ACCOUNT(21, "Expired Account Token"),
    ACTIVATOR_ACCOUNT_ALREADY_ACTIVATED(22, "The account was already activated"),
    ACTIVATOR_ACCOUNT_NOT_FOUND(23, "{custom message}"),

    INITIALIZER_STARTED(24, "The INITIALIZER has been started"),
    INITIALIZER_TOKEN_OK(25, "{custom message}"),
    INITIALIZER_ERROR(26, "The current user was not activated"),
    INITIALIZER_ENVIRONMENT_OK(27, "The environment has been inialized"),
    INITIALIZER_SESSION_PREPARE_OK(27, "The session has been configured"),
    INITIALIZER_GLASS_STARTED(28, "The INITIALIZER glass was called"),
    INITIALIZER_EXCEPTION(29, "{custom message}"),
    INITIALIZER_DENIED(30, "Access denied, missing token"),
    INITIALIZER_BURNED(31, "The INITIALIZER was burned"),
    INITIALIZER_SUCCESSFUL(32, "The INITIALIZER has been finished"),
    INITIALIZER_SESSION_NOT_FOUND(33, "The session was not found to INITIALIZER"),
    INITIALIZER_FORM_STARTED(34, "The INITIALIZER form was called"),

    SWAGGER_ROUTER_SIGN(35, "The SWAGGER ROUTER was posted to sign"),
    SWAGGER_ROUTER_DETAILS(36, "{custom message}"),
    SWAGGER_ROUTER_STOPBY_SHIELD(37, "The request has been stopped by shiled"),
    SWAGGER_ROUTER_MISSING_USERNAME(38, "The username received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_MISSING_PASSWORD(39, "The password received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXPIRED_SESSION(40, "The session was expired in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXCEPTION(41, "{custom message}"),
    SWAGGER_ROUTER_SESSION_FOUNDED(42, "The current request was running at moment"),
    SWAGGER_ROUTER_LOGIN_ERROR(43, "{custom message}"),
    SWAGGER_ROUTER_LOGIN_OK(44, "{custom message}"),
    SWAGGER_ROUTER_REFRESH_STARTED(45, "The refresh was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_REFRESH_OK(46, "The refresh was finished in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ROUTES_STARTED(47, "The routes was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_DENIED_STARTED(48, "The denied was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ERROR_STARTED(49, "{custom message}"),

    PASSWORD_STARTED(50, "The PASSWORD process has been started"),
    PASSWORD_GLASS_STARTED(51, "The PASSWORD glass has been started"),
    PASSWORD_EXCEPTION(52, "{custom message}"),
    PASSWORD_GLASS_EXCEPTION(53, "{custom message}"),
    PASSWORD_FORM_STARTED(54, "The PASSWORD form has been loaded"),
    PASSWORD_FORM_INVALID_ACCCESS(55, "The APD-USER-PASSWORD session was not ok"),
    PASSWORD_VIEW_FORM(56, "View password was called by PASSWORD"),
    PASSWORD_CHANGED_SUCCESSFUL(57, "An password was changed from PASSWORD"),
    PASSWORD_DATA_POST(58, "Was posted to create a new account from PASSWORD"),
    PASSWORD_FORM_INVALID_SESSION(59, "Invalid session to change a password"),
    PASSWORD_MAIL_SENDER_OK(60, "The mail has been sended to user"),
    PASSWORD_ACCOUNT_NOT_FOUND(61, "{custom message}"),

    PASSWORD_RECOVERY_STARTED(62, "The PASSWORD RECOVERY process has been started"),
    PASSWORD_RECOVERY_GLASS_STARTED(63, "The PASSWORD RECOVERY glass has been started"),
    PASSWORD_RECOVERY_EXCEPTION(64, "{custom message}"),
    PASSWORD_RECOVERY_GLASS_EXCEPTION(65, "{custom message}"),
    PASSWORD_RECOVERY_FORM_STARTED(66, "The PASSWORD RECOVERY form has been loaded"),
    PASSWORD_RECOVERY_FORM_INVALID_ACCCESS(67, "The APD-USER-PASSWORD-RECOVERY session was not ok"),
    PASSWORD_RECOVERY_VIEW_FORM(68, "View password was called by PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_SUCCESSFUL(69, "An password was recovered from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_DATA_POST(70, "Was posted to create a new account from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_FORM_INVALID_SESSION(71, "Invalid session to recovery a password"),
    PASSWORD_RECOVERY_MAIL_SENDER_OK(72, "The mail has been sended to user"),
    PASSWORD_RECOVERY_USER_NOT_FOUND(73, "{custom message}"),

    RECOVERY_STARTED(74, "The RECOVERY account has been started"),
    RECOVERY_GLASS_STARTED(75, "The RECOVERY glass has been started"),
    RECOVERY_EXCEPTION(76, "{custom message}"),
    RECOVERY_GLASS_EXCEPTION(77, "{custom message}"),
    RECOVERY_FORM_STARTED(78, "The RECOVERY form has been loaded"),
    RECOVERY_FORM_INVALID_ACCCESS(79, "The APD-USER-RECOVERY session was not ok"),
    RECOVERY_VIEW_FORM(80, "View Form was called by RECOVERY"),
    RECOVERY_ACCOUNT_SUCCESSFUL(81, "An account was recovered from RECOVERY"),
    RECOVERY_DATA_POST(82, "Was posted to recovery a account from RECOVERY"),
    RECOVERY_FORM_INVALID_SESSION(83, "Invalid session to recovery acccount"),
    RECOVERY_FORM_USER_ALREADY_EXISTS(84, "The user or email already exists"),
    RECOVERY_FORM_USER_CREATED(85, "The user was recovered successful"),
    RECOVERY_MAIL_SENDER_OK(86, "The mail has been sended to user"),

    SENTINEL_ALLOWED_STARTED(87, "The allowed path on SENTINEL has been started"),
    SENTINEL_ALLOWED_FINISHED(88, "The allowed path on SENTINEL has been finished"),
    SENTINEL_DOCS_STARTED(89, "The docs path on SENTINEL has been started"),
    SENTINEL_DOCS_FINISHED_FORM(90, "The docs path on SENTINEL has been finished with form"),
    SENTINEL_DOCS_FINISHED_CAPTOR(91, "The docs path on SENTINEL has been finished with captor"),
    SENTINEL_PROTECT_STARTED(92, "The protect path on SENTINEL has been started"),
    SENTINEL_ROUTER_STARTED(93, "The router path on SENTINEL has been started"),
    SENTINEL_LOGOUT_STARTED(94, "The router path on SENTINEL has been started"),
    SENTINEL_PROTECTOR_STARTED(95, "The protector path on SENTINEL has been started"),
    SENTINEL_ERROR_STARTED(96, "The error path on SENTINEL has been started"),

    FORWARD_TO_GENERATOR_GLASS(97, "forward: forwardToGeneratorGlass was running"),
    FORWARD_TO_RECOVERY_GLASS(98, "forward: forwardToRecoveryGlass was running"),
    FORWARD_TO_PASSWORD_GLASS(99, "forward: forwardToPasswordGlass was running"),
    FORWARD_TO_PASSWORD_RECOVERY_GLASS(100, "forward: forwardToPasswordRecoveryGlass was running"),
    FORWARD_TO_GLASS(101, "forward: forwardToGlass was running"),
    REDIRECT_TO_GENERATOR_FORM(102, "redirect: redirecting to form was running"),
    REDIRECT_TO_GENERATOR_FORM_TARGET(103, "{custom message}"),
    REDIRECT_TO_RECOVERY_FORM(104, "redirect: redirecting to form was running"),
    REDIRECT_TO_RECOVERY_FORM_TARGET(105, "{custom message}"),
    REDIRECT_TO_PASSWORD_FORM(106, "redirect: redirecting to form was running"),
    REDIRECT_TO_PASSWORD_FORM_TARGET(107, "{custom message}"),
    REDIRECT_TO_PASSWORD_RECOVERY_FORM(108, "redirect: redirecting to form was running"),
    REDIRECT_TO_PASSWORD_RECOVERY_FORM_TARGET(109, "redirect: redirectToPasswordRecoveryForm"),
    REDIRECT_TO_FORM_STARTED(110, "recirect: redirectToForm was running"),
    REDIRECT_TO_FORM_EXPIRED(111, "The session ADP-EXPIRED-SESSION was not ok"),
    REDIRECT_TO_FORM_FINISHED(112, "recirect: redirectToForm was finished"),
    REDIRECT_EXPIRED_SESSION_STARTED(113, "The redirectExpiredSession was called"),
    REDIRECT_EXPIRED_SESSION_FINISHED(114, "{custom message}"),
    CAPTOR_STARTED(115, "The captor was called in the REDIRECT"),
    CAPTOR_REDIRECT_TO_PROTECTOR(116, "The captor has been redirected to PROTECTOR"),
    CAPTOR_REDIRECT_TO_ROUTER(117, "The captor has been redirected to ROUTER"),
    ROUTER_STARTED(118, "The router was called in the REDIRECT"),
    ROUTER_REDIRECT_TO_SWAGGER_UI(119, "The captor has been redirected to SWAGGER_UI"),
    ROUTER_REDIRECT_TO_PROTECTOR(120, "The captor has been redirected to PROTECTOR"),
    REDIRECT_LOGOUT_STARTED(121, "The logout has been started"),
    REDIRECT_LOGOUT_TO_LOGIN(122, "redirect: logout"),

    LIBRARY_ENVIRONMENT_STARTED(123, "[IMPORTANT] The env was started"),
    LIBRARY_SESSION_PREPARED_OK(124, "Session created successful"),
    LIBRARY_SESSION_RENEW_OK(125, "Session renewed successful"),
    LIBRARY_SESSION_CONTROL_DISABLED(126, "[WARNING] Session control was disabled"),
    LIBRARY_SESSION_EXPIRED(127, "Session expired"),
    LIBRARY_SESSION_RENEWED(128, "Session renew successful"),
    LIBRARY_ACCOUNT_ALREADY_ACTIVATED(129, "Account already activated in another time"),
    LIBRARY_ACCOUNT_NOT_ACTIVATED_YET(130, "The account was not activated yet"),
    LIBRARY_LOGIN_SUCCESSFUL(131, "{custom message}"),
    LIBRARY_LOGIN_ERROR(132, "{custom message}"),
    LIBRARY_GENERATOR_USER_ALREADY_EXISTS(133, "{custom message}"),
    LIBRARY_GENERATOR_USER_SUCCESSFUL(134, "{custom message}"),
    LIBRARY_USER_RECOVERY_OK(135, "{custom message}"),
    LIBRARY_PASSWORD_UPDATED(136, "{custom message}"),
    LIBRARY_SESSION_FOUNDED(137, "Session founded successful"),

    SECURITY_FIREWALL_STARTED(138, "The firewall in SECURITY has been started"),
    SECURITY_FIREWALL_FINISHED(139, "The firewall in SECURITY has been finished"),
    SECURITY_BURN_STARTED(140, "The burn in SECURITY has been started"),
    SECURITY_BURN_FINISHED_TRUE(141, "The burn in SECURITY has been finished with TRUE"),
    SECURITY_BURN_FINISHED_FALSE(142, "The burn in SECURITY has been finished with FALSE"),
    SECURITY_SHIELD_STARTED(143, "The shield in SECURITY has been started"),

    MAILSENDER_STARTED(144, "The MAILSENDER was started"),
    MAILSENDER_CONTENT(145, "{custom message}"),

    VIEW_ERROR_STARTED(146, "The view ERROR has been started"),
    VIEW_ERROR_FINISHED(147, "The view ERROR has been finished"),

    VIEW_GENERATOR_STARTED(148, "The view GENERATOR has been started"),
    VIEW_GENERATOR_FINISHED(149, "The view GENERATOR has been finished"),
    VIEW_GENERATOR_ERROR(150, "{custom message}"),
    VIEW_GENERATOR_EXCEPTION(151, "{custom message}"),

    VIEW_RECOVERY_STARTED(152, "The view RECOVERY has been started"),
    VIEW_RECOVERY_FINISHED(153, "The view RECOVERY has been finished"),
    VIEW_RECOVERY_ERROR(154, "{custom message}"),
    VIEW_RECOVERY_EXCEPTION(155, "{custom message}"),

    VIEW_PASSWORD_STARTED(156, "The view PASSWORD has been started"),
    VIEW_PASSWORD_FINISHED(157, "The view PASSWORD has been finished"),
    VIEW_PASSWORD_ERROR(158, "{custom message}"),
    VIEW_PASSWORD_EXCEPTION(159, "{custom message}"),

    VIEW_PASSWORD_RECOVERY_STARTED(160, "The view PASSWORD RECOVERY has been started"),
    VIEW_PASSWORD_RECOVERY_FINISHED(161, "The view PASSWORD RECOVERY has been finished"),
    VIEW_PASSWORD_RECOVERY_ERROR(162, "{custom message}"),
    VIEW_PASSWORD_RECOVERY_EXCEPTION(163, "{custom message}"),

    VIEW_FORM_STARTED(164, "The view FORM has been started"),
    VIEW_FORM_FINISHED(165, "The view FORM has been finished"),
    VIEW_FORM_ERROR(166, "{custom message}"),
    VIEW_FORM_EXCEPTION(167, "{custom message}"),

    VIEW_INDEX_STARTED(168, "The view INDEX has been started"),
    VIEW_INDEX_FINISHED(169, "The view INDEX has been finished"),
    VIEW_INDEX_ERROR(170, "{custom message}"),
    VIEW_INDEX_EXCEPTION(171, "{custom message}"),

    VIEW_REFRESHED_STARTED(172, "The view REFRESH has been started"),
    VIEW_REFRESHED_FINISHED(173, "The view REFRESH has been finished"),
    VIEW_REFRESHED_ERROR(174, "{custom message}"),
    VIEW_REFRESHED_EXCEPTION(175, "{custom message}"),

    VIEW_PROTECTOR_STARTED(176, "The view PROTECTOR has been started"),
    VIEW_PROTECTOR_FINISHED(177, "The view PROTECTOR has been finished"),
    VIEW_PROTECTOR_ERROR(178, "{custom message}"),
    VIEW_PROTECTOR_EXCEPTION(179, "{custom message}"),

    GENERIC_MESSAGE(20000, ""),
    NO_MAPPING_FOUND(20001, "No mappging found");

    public int code;
    public String message;

}
