package com.apidocprotector.enumerator;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ApiDocProtectorRegisterEnum {

    GENERATOR_STARTED(1000, "The GENERATOR form to new account has been started"),
    GENERATOR_GLASS_STARTED(1001, "The GENERATOR glass has been started"),
    GENERATOR_EXCEPTION(1002, "Occurs an error on GENERATOR process"),
    GENERATOR_GLASS_EXCEPTION(1003, "Occurs an error on GENERATOR GLASS process"),
    GENERATOR_FORM_STARTED(1004, "The GENERATOR form to new account has been loaded"),
    GENERATOR_FORM_INVALID_ACCCESS(1005, "The APD-USER-GENERATOR session was not ok"),
    GENERATOR_VIEW_FORM(7, "View Form was called by GENERATOR"),
    GENERATOR_ACCOUNT_CREATED(1006, "An account was created from GENERATOR"),
    GENERATOR_DATA_POST(1007, "Was posted to create a new account from GENERATOR"),
    GENERATOR_FORM_INVALID_SESSION(1008, "Invalid session to create a new acccount"),
    GENERATOR_FORM_USER_ALREADY_EXISTS(1009, "The user or email already exists"),
    GENERATOR_MAIL_SENDER_OK(1010, "The mail has been sended to user"),
    GENERATOR_FORM_INVALID_EMAIL(1011, "The mail address is not valid"),

    ACTIVATOR_STARTED(2000, "The ACTIVATOR account has been started"),
    ACTIVATOR_TOKEN_OK(2001, "The current token was ok"),
    ACTIVATOR_MAIL_SUCCESSFUL(2002, "An email has been sent to current user account"),
    ACTIVATOR_FINISHED(2003, "The ACTIVATOR finished successful"),
    ACTIVATOR_EXPIRED_ACCOUNT(2004, "Expired Account Token"),
    ACTIVATOR_ACCOUNT_ALREADY_ACTIVATED(2005, "The account was already activated"),
    ACTIVATOR_ACCOUNT_NOT_FOUND(2006, "Account not found to activate"),

    INITIALIZER_STARTED(3000, "The INITIALIZER has been started"),
    INITIALIZER_TOKEN_OK(3001, "Token started successful in the INITIALIZER"),
    INITIALIZER_ERROR(3002, "The current user was not activated"),
    INITIALIZER_ENVIRONMENT_OK(3003, "The environment has been inialized"),
    INITIALIZER_SESSION_PREPARE_OK(3004, "The session has been configured"),
    INITIALIZER_GLASS_STARTED(3005, "The INITIALIZER glass was called"),
    INITIALIZER_EXCEPTION(3006, "Occurs an error on INITIALIZER process"),
    INITIALIZER_DENIED(3007, "Access denied, missing token"),
    INITIALIZER_BURNED(3008, "The INITIALIZER was burned"),
    INITIALIZER_SUCCESSFUL(3009, "The INITIALIZER has been finished"),
    INITIALIZER_SESSION_NOT_FOUND(3010, "The session was not found to INITIALIZER"),
    INITIALIZER_FORM_STARTED(3011, "The INITIALIZER form was called"),

    SWAGGER_ROUTER_SIGN(4000, "The SWAGGER ROUTER was posted to sign"),
    SWAGGER_ROUTER_DETAILS(4001, "{custom message}"),
    SWAGGER_ROUTER_STOPPED_BY_SHIELD(4002, "The request has been stopped by shiled"),
    SWAGGER_ROUTER_MISSING_USERNAME(4003, "The username received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_MISSING_PASSWORD(4004, "The password received was empty in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXPIRED_SESSION(4005, "The session was expired in SWAGGER ROUTER"),
    SWAGGER_ROUTER_EXCEPTION(4006, "{custom message}"),
    SWAGGER_ROUTER_SESSION_FOUNDED(4007, "The current request was running at moment"),
    SWAGGER_ROUTER_LOGIN_ERROR(4008, "{custom message}"),
    SWAGGER_ROUTER_LOGIN_OK(4009, "{custom message}"),
    SWAGGER_ROUTER_REFRESH_STARTED(4010, "The refresh was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_REFRESH_OK(4011, "The refresh was finished in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ROUTES_STARTED(4012, "The routes was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_DENIED_STARTED(4013, "The denied was started in the SWAGGER ROUTER"),
    SWAGGER_ROUTER_ERROR_STARTED(4014, "{custom message}"),

    PASSWORD_STARTED(5000, "The PASSWORD process has been started"),
    PASSWORD_GLASS_STARTED(5001, "The PASSWORD glass has been started"),
    PASSWORD_EXCEPTION(5002, "{custom message}"),
    PASSWORD_GLASS_EXCEPTION(5003, "{custom message}"),
    PASSWORD_FORM_STARTED(5004, "The PASSWORD form has been loaded"),
    PASSWORD_FORM_INVALID_ACCCESS(5005, "The APD-USER-PASSWORD session was not ok"),
    PASSWORD_VIEW_FORM(5006, "View password was called by PASSWORD"),
    PASSWORD_CHANGED_SUCCESSFUL(5007, "An password was changed from PASSWORD"),
    PASSWORD_DATA_POST(5008, "Was posted to create a new account from PASSWORD"),
    PASSWORD_FORM_INVALID_SESSION(5009, "Invalid session to change a password"),
    PASSWORD_MAIL_SENDER_OK(5010, "The mail has been sended to user"),
    PASSWORD_ACCOUNT_NOT_FOUND(5011, "{custom message}"),
    PASSWORD_FORM_INVALID_EMAIL(5012, "The mail address is not valid"),

    PASSWORD_RECOVERY_STARTED(6000, "The PASSWORD RECOVERY process has been started"),
    PASSWORD_RECOVERY_GLASS_STARTED(6001, "The PASSWORD RECOVERY glass has been started"),
    PASSWORD_RECOVERY_EXCEPTION(6002, "PASSWORD RECOVERY EXCEPTION"),
    PASSWORD_RECOVERY_GLASS_EXCEPTION(6003, "{custom message}"),
    PASSWORD_RECOVERY_FORM_STARTED(6004, "The PASSWORD RECOVERY form has been loaded"),
    PASSWORD_RECOVERY_FORM_INVALID_ACCCESS(6005, "The APD-USER-PASSWORD-RECOVERY session was not ok"),
    PASSWORD_RECOVERY_VIEW_FORM(6006, "View password was called by PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_SUCCESSFUL(6007, "An password was recovered from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_DATA_POST(6008, "Was posted to create a new account from PASSWORD RECOVERY"),
    PASSWORD_RECOVERY_FORM_INVALID_SESSION(6009, "Invalid session to recovery a password"),
    PASSWORD_RECOVERY_MAIL_SENDER_OK(6010, "The mail has been sended to user"),
    PASSWORD_RECOVERY_USER_NOT_FOUND(6011, "{custom message}"),

    RECOVERY_STARTED(7000, "The RECOVERY account has been started"),
    RECOVERY_GLASS_STARTED(7001, "The RECOVERY glass has been started"),
    RECOVERY_EXCEPTION(7002, "{custom message}"),
    RECOVERY_GLASS_EXCEPTION(7003, "{custom message}"),
    RECOVERY_FORM_STARTED(7004, "The RECOVERY form has been loaded"),
    RECOVERY_FORM_INVALID_ACCCESS(7005, "The APD-USER-RECOVERY session was not ok"),
    RECOVERY_VIEW_FORM(7006, "View Form was called by RECOVERY"),
    RECOVERY_ACCOUNT_SUCCESSFUL(7007, "An account was recovered from RECOVERY"),
    RECOVERY_DATA_POST(7008, "Was posted to recovery a account from RECOVERY"),
    RECOVERY_FORM_INVALID_SESSION(7009, "Invalid session to recovery acccount"),
    RECOVERY_FORM_USER_ALREADY_EXISTS(7010, "The user or email already exists"),
    RECOVERY_FORM_USER_CREATED(7011, "The user was recovered successful"),
    RECOVERY_MAIL_SENDER_OK(7012, "The mail has been sended to user"),
    RECOVERY_FORM_INVALID_EMAIL(7013, "The mail address is not valid"),

    SENTINEL_ALLOWED_STARTED(8000, "The allowed path on SENTINEL has been started"),
    SENTINEL_ALLOWED_FINISHED(8001, "The allowed path on SENTINEL has been finished"),
    SENTINEL_DOCS_STARTED(8002, "The docs path on SENTINEL has been started"),
    SENTINEL_DOCS_FINISHED_FORM(8003, "The docs path on SENTINEL has been finished with form"),
    SENTINEL_DOCS_FINISHED_CAPTOR(8004, "The docs path on SENTINEL has been finished with captor"),
    SENTINEL_PROTECT_STARTED(8005, "The protect path on SENTINEL has been started"),
    SENTINEL_ROUTER_STARTED(8006, "The router path on SENTINEL has been started"),
    SENTINEL_LOGOUT_STARTED(8007, "The router path on SENTINEL has been started"),
    SENTINEL_PROTECTOR_STARTED(8008, "The protector path on SENTINEL has been started"),
    SENTINEL_ERROR_STARTED(8009, "The error path on SENTINEL has been started"),

    FORWARD_TO_GENERATOR_GLASS(9000, "forward: forwardToGeneratorGlass was running"),
    FORWARD_TO_RECOVERY_GLASS(9001, "forward: forwardToRecoveryGlass was running"),
    FORWARD_TO_PASSWORD_GLASS(9002, "forward: forwardToPasswordGlass was running"),
    FORWARD_TO_PASSWORD_RECOVERY_GLASS(9003, "forward: forwardToPasswordRecoveryGlass was running"),
    FORWARD_TO_GLASS(9004, "forward: forwardToGlass was running"),
    REDIRECT_TO_GENERATOR_FORM(9005, "redirect: redirecting to form was running"),
    REDIRECT_TO_GENERATOR_FORM_TARGET(9006, "{custom message}"),
    REDIRECT_TO_RECOVERY_FORM(9007, "redirect: redirecting to form was running"),
    REDIRECT_TO_RECOVERY_FORM_TARGET(9008, "{custom message}"),
    REDIRECT_TO_PASSWORD_FORM(9009, "redirect: redirecting to form was running"),
    REDIRECT_TO_PASSWORD_FORM_TARGET(9010, "{custom message}"),
    REDIRECT_TO_PASSWORD_RECOVERY_FORM(9011, "redirect: redirecting to form was running"),
    REDIRECT_TO_PASSWORD_RECOVERY_FORM_TARGET(9012, "redirect: redirectToPasswordRecoveryForm"),
    REDIRECT_TO_FORM_STARTED(9013, "recirect: redirectToForm was running"),
    REDIRECT_TO_FORM_EXPIRED(9014, "The session ADP-EXPIRED-SESSION was not ok"),
    REDIRECT_TO_FORM_FINISHED(9015, "recirect: redirectToForm was finished"),
    REDIRECT_EXPIRED_SESSION_STARTED(9016, "The redirectExpiredSession was called"),
    REDIRECT_EXPIRED_SESSION_FINISHED(9017, "{custom message}"),
    CAPTOR_STARTED(9018, "The captor was called in the REDIRECT"),
    CAPTOR_REDIRECT_TO_PROTECTOR(9019, "The captor has been redirected to PROTECTOR"),
    CAPTOR_REDIRECT_TO_ROUTER(9020, "The captor has been redirected to ROUTER"),
    ROUTER_STARTED(9021, "The router was called in the REDIRECT"),
    ROUTER_REDIRECT_TO_SWAGGER_UI(9022, "The captor has been redirected to SWAGGER_UI"),
    ROUTER_REDIRECT_TO_PROTECTOR(9023, "The captor has been redirected to PROTECTOR"),
    REDIRECT_LOGOUT_STARTED(9024, "The logout has been started"),
    REDIRECT_LOGOUT_TO_LOGIN(9025, "redirect: logout"),

    LIBRARY_ENVIRONMENT_STARTED(10000, "[IMPORTANT] The env was started"),
    LIBRARY_SESSION_PREPARED_OK(10001, "Session created successful"),
    LIBRARY_SESSION_RENEW_OK(10002, "Session renewed successful"),
    LIBRARY_SESSION_CONTROL_DISABLED(10003, "[WARNING] Session control was disabled"),
    LIBRARY_SESSION_EXPIRED(10004, "Session expired"),
    LIBRARY_SESSION_RENEWED(10005, "Session renew successful"),
    LIBRARY_ACCOUNT_ALREADY_ACTIVATED(10006, "Account already activated in another time"),
    LIBRARY_ACCOUNT_NOT_ACTIVATED_YET(10007, "The account was not activated yet"),
    LIBRARY_LOGIN_SUCCESSFUL(10008, "{custom message}"),
    LIBRARY_LOGIN_ERROR(10009, "{custom message}"),
    LIBRARY_GENERATOR_USER_ALREADY_EXISTS(10010, "{custom message}"),
    LIBRARY_GENERATOR_USER_SUCCESSFUL(10011, "{custom message}"),
    LIBRARY_USER_RECOVERY_OK(10012, "{custom message}"),
    LIBRARY_PASSWORD_UPDATED(10013, "{custom message}"),
    LIBRARY_SESSION_FOUNDED(10014, "Session founded successful"),

    SECURITY_FIREWALL_STARTED(11015, "The firewall in SECURITY has been started"),
    SECURITY_FIREWALL_FINISHED(11016, "The firewall in SECURITY has been finished"),
    SECURITY_BURN_STARTED(11017, "The burn in SECURITY has been started"),
    SECURITY_BURN_FINISHED_TRUE(11018, "The burn in SECURITY has been finished with TRUE"),
    SECURITY_BURN_FINISHED_FALSE(11019, "The burn in SECURITY has been finished with FALSE"),
    SECURITY_SHIELD_STARTED(11020, "The shield in SECURITY has been started"),

    MAILSENDER_STARTED(12000, "The MAILSENDER was started"),
    MAILSENDER_CONTENT(12001, "{custom message}"),

    VIEW_ERROR_STARTED(13000, "The view ERROR has been started"),
    VIEW_ERROR_FINISHED(13001, "The view ERROR has been finished"),

    VIEW_GENERATOR_STARTED(14000, "The view GENERATOR has been started"),
    VIEW_GENERATOR_FINISHED(14001, "The view GENERATOR has been finished"),
    VIEW_GENERATOR_ERROR(14002, "{custom message}"),
    VIEW_GENERATOR_EXCEPTION(14003, "{custom message}"),

    VIEW_RECOVERY_STARTED(15000, "The view RECOVERY has been started"),
    VIEW_RECOVERY_FINISHED(15001, "The view RECOVERY has been finished"),
    VIEW_RECOVERY_ERROR(15002, "{custom message}"),
    VIEW_RECOVERY_EXCEPTION(15003, "{custom message}"),

    VIEW_PASSWORD_STARTED(16000, "The view PASSWORD has been started"),
    VIEW_PASSWORD_FINISHED(16001, "The view PASSWORD has been finished"),
    VIEW_PASSWORD_ERROR(16002, "{custom message}"),
    VIEW_PASSWORD_EXCEPTION(16003, "{custom message}"),

    VIEW_PASSWORD_RECOVERY_STARTED(17000, "The view PASSWORD RECOVERY has been started"),
    VIEW_PASSWORD_RECOVERY_FINISHED(17001, "The view PASSWORD RECOVERY has been finished"),
    VIEW_PASSWORD_RECOVERY_ERROR(17002, "{custom message}"),
    VIEW_PASSWORD_RECOVERY_EXCEPTION(17003, "{custom message}"),

    VIEW_FORM_STARTED(18000, "The view FORM has been started"),
    VIEW_FORM_FINISHED(18001, "The view FORM has been finished"),
    VIEW_FORM_ERROR(18002, "{custom message}"),
    VIEW_FORM_EXCEPTION(18003, "{custom message}"),

    VIEW_INDEX_STARTED(19000, "The view INDEX has been started"),
    VIEW_INDEX_FINISHED(19001, "The view INDEX has been finished"),
    VIEW_INDEX_ERROR(19002, "{custom message}"),
    VIEW_INDEX_EXCEPTION(19003, "{custom message}"),

    VIEW_REFRESHED_STARTED(20000, "The view REFRESH has been started"),
    VIEW_REFRESHED_FINISHED(20001, "The view REFRESH has been finished"),
    VIEW_REFRESHED_ERROR(20002, "{custom message}"),
    VIEW_REFRESHED_EXCEPTION(20003, "{custom message}"),

    VIEW_PROTECTOR_STARTED(21000, "The view PROTECTOR has been started"),
    VIEW_PROTECTOR_FINISHED(21001, "The view PROTECTOR has been finished"),
    VIEW_PROTECTOR_ERROR(21002, "{custom message}"),
    VIEW_PROTECTOR_EXCEPTION(21003, "{custom message}"),

    GENERIC_MESSAGE(22000, ""),
    NO_MAPPING_FOUND(22001, "No mappging found"),
    NO_AUDITOR(22002, null);

    public int code;
    public String message;

}
